<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220415185341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблицы со статусами';
    }

    public function up(Schema $schema): void
    {
   $sql=
       <<<EOF
create table status
(
    id int primary key generated by default as identity,
    name varchar(150) unique 
)

EOF;

   $this->addSql($sql);

    }

    public function down(Schema $schema): void
    {
        $this->addSql('drop table status');

    }
}
